### ISSUE TITLE
There is no feign-java11 in feign-bom

### ISSUE THREAD

**Issue by krzyk** [OpenFeign/feign#1253]
I just checked feign-bom and there is no feign-java11 (or feign-java8) in all boms since >= 10.2.0, I checked couple of newest ones and I didn't see any place with feign-java11 and feign-java8 was only in <=10.4.0.

Could this be added to bom?

**Comment by kdavisk6** [comment]
@krzyk 

2 points here.  Feign-Java8 was retired when we updated our baseline builds to be java 8, so there is no need to continue to include the module.  It was folded into core.

For Feign-Java11, there are two things going on here, first is that our release builds were being executed on Java8 only, so the `feign-java11` was not included by mistake.  This has been fixed, or should be for the most recent releases.  Second, `feign-java11` is considered experimental and we don't typically include experimental modules in the `bom`.  However, I see no harm in adding it now.  Would you like to submit a PR for that?

**Comment by krzyk** [comment]
@kdavisk6 Sure, I'll provide PR

**Comment by krzyk** [comment]
@kdavisk6 I looked at this, and when I build from master or from e.g. 10.11 tag I get a bom that has feign-java11 inside.
Does the final build (that ends up in maven central) adds some bom filtering?

**Comment by kdavisk6** [comment]
Our release builds in Travis run on JDK8, which will filter out the `feign-java11`.  It looks like we'll have to change our release process to handle this module.  Apologies.  We'll have to look into this.

**Comment by kdavisk6** [comment]
This has been fixed for all releases since 10.10

**Comment by czubin** [comment]
@kdavisk6 

I want to point out that java11 is still not included in the feign bom. 
It seems the BOM generation plugin only take dependencies that are included in the parent pom. Java11 is absent as module.

As shown in: https://repo1.maven.org/maven2/io/github/openfeign/feign-bom/11.6/feign-bom-11.6.pom

**Comment by velo** [comment]
Due the need to build feign with Java 8, I don't think we can include this
module on the auto generated bom
